// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// int_get_plist
CharacterVector int_get_plist(RawVector r);
RcppExport SEXP _plist_int_get_plist(SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(int_get_plist(r));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_plist_int_get_plist", (DL_FUNC) &_plist_int_get_plist, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_plist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
